# Generated by Django 5.2.11 on 2026-09-16 14:10

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("contenttypes", "0002_remove_content_type_name"),
    ]

    operations = [
        migrations.CreateModel(
            name="Region",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=120)),
                ("slug", models.SlugField(max_length=140, unique=True)),
                ("iso2", models.CharField(blank=True, max_length=2)),
                ("continent", models.CharField(blank=True, max_length=40)),
            ],
            options={
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="Series",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("title", models.CharField(max_length=300)),
                ("slug", models.SlugField(max_length=320, unique=True)),
                ("description", models.TextField(blank=True)),
                ("starts_on", models.DateField(blank=True, null=True)),
                ("ends_on", models.DateField(blank=True, null=True)),
                ("location", models.CharField(blank=True, max_length=200)),
                ("is_active", models.BooleanField(default=True)),
            ],
            options={
                "verbose_name_plural": "series",
                "ordering": ["-starts_on", "title"],
            },
        ),
        migrations.CreateModel(
            name="Video",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "youtube_id",
                    models.CharField(db_index=True, max_length=16, unique=True),
                ),
                ("title", models.CharField(blank=True, max_length=300)),
                ("slug", models.SlugField(blank=True, max_length=320, unique=True)),
                (
                    "duration_seconds",
                    models.PositiveIntegerField(blank=True, null=True),
                ),
                ("published_at", models.DateTimeField(blank=True, null=True)),
                (
                    "availability",
                    models.CharField(
                        choices=[
                            ("available", "Available"),
                            ("unavailable", "Unavailable"),
                            ("unknown", "Not checked"),
                        ],
                        db_index=True,
                        default="unknown",
                        help_text="Checked against the YouTube thumbnail CDN.",
                        max_length=12,
                    ),
                ),
                ("last_checked_at", models.DateTimeField(blank=True, null=True)),
                (
                    "allow_embed",
                    models.BooleanField(
                        default=True,
                        help_text="Uncheck to link out to YouTube instead of embedding.",
                    ),
                ),
                ("thumbnail_override", models.URLField(blank=True)),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="Category",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=120)),
                ("slug", models.SlugField(max_length=140, unique=True)),
                ("description", models.TextField(blank=True)),
                ("order", models.PositiveIntegerField(default=0)),
                ("is_active", models.BooleanField(default=True)),
                (
                    "parent",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="children",
                        to="content.category",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "categories",
                "ordering": ["order", "name"],
            },
        ),
        migrations.CreateModel(
            name="ContentItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "kind",
                    models.CharField(
                        choices=[
                            ("teaching", "Teaching"),
                            ("prophecy", "Prophecy"),
                            ("healing", "Healing"),
                            ("writing", "Writing"),
                        ],
                        db_index=True,
                        max_length=16,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[("draft", "Draft"), ("published", "Published")],
                        db_index=True,
                        default="draft",
                        max_length=12,
                    ),
                ),
                ("title", models.CharField(max_length=500)),
                ("title_source", models.CharField(blank=True, max_length=500)),
                ("title_yt", models.CharField(blank=True, max_length=500)),
                ("slug", models.SlugField(max_length=520, unique=True)),
                ("kicker", models.CharField(blank=True, max_length=80)),
                ("speaker", models.CharField(blank=True, max_length=200)),
                ("summary", models.TextField(blank=True)),
                ("body", models.TextField(blank=True, help_text="Markdown.")),
                (
                    "position_in_series",
                    models.PositiveIntegerField(blank=True, null=True),
                ),
                (
                    "published_at",
                    models.DateTimeField(blank=True, db_index=True, null=True),
                ),
                (
                    "prophecy_date",
                    models.DateField(blank=True, db_index=True, null=True),
                ),
                (
                    "date_source",
                    models.CharField(
                        choices=[
                            ("title_parsed", "Parsed from title"),
                            ("manual", "Entered by staff"),
                            ("unknown", "Undated"),
                        ],
                        default="unknown",
                        max_length=16,
                    ),
                ),
                (
                    "date_precision",
                    models.CharField(
                        choices=[
                            ("day", "Day"),
                            ("month", "Month"),
                            ("year", "Year"),
                            ("unknown", "Unknown"),
                        ],
                        default="unknown",
                        max_length=8,
                    ),
                ),
                ("is_fulfilled", models.BooleanField(db_index=True, default=False)),
                ("fulfillment_summary", models.TextField(blank=True)),
                (
                    "condition",
                    models.CharField(
                        blank=True,
                        help_text="Healings: the condition reported.",
                        max_length=200,
                    ),
                ),
                (
                    "is_anonymous",
                    models.BooleanField(
                        default=True,
                        help_text="Healings: keep the person unnamed unless consent is on file.",
                    ),
                ),
                ("is_featured", models.BooleanField(default=False)),
                ("needs_review", models.BooleanField(db_index=True, default=False)),
                (
                    "confidence",
                    models.FloatField(
                        default=0.0,
                        help_text="Auto-classification confidence, 0-1. Below 0.8 needs review.",
                    ),
                ),
                ("source_order", models.PositiveIntegerField(blank=True, null=True)),
                (
                    "import_key",
                    models.CharField(blank=True, db_index=True, max_length=64),
                ),
                ("import_hash", models.CharField(blank=True, max_length=64)),
                ("imported_values", models.JSONField(blank=True, default=dict)),
                ("import_conflicts", models.JSONField(blank=True, default=list)),
                (
                    "language",
                    models.CharField(db_index=True, default="en", max_length=8),
                ),
                (
                    "translation_group",
                    models.UUIDField(db_index=True, default=uuid.uuid4),
                ),
                (
                    "category",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="items",
                        to="content.category",
                    ),
                ),
                (
                    "regions",
                    models.ManyToManyField(
                        blank=True, related_name="items", to="content.region"
                    ),
                ),
                (
                    "series",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="items",
                        to="content.series",
                    ),
                ),
            ],
            options={
                "ordering": ["-published_at", "-created_at"],
            },
        ),
        migrations.CreateModel(
            name="Healing",
            fields=[],
            options={
                "proxy": True,
                "indexes": [],
                "constraints": [],
            },
            bases=("content.contentitem",),
        ),
        migrations.CreateModel(
            name="Prophecy",
            fields=[],
            options={
                "verbose_name_plural": "prophecies",
                "proxy": True,
                "indexes": [],
                "constraints": [],
            },
            bases=("content.contentitem",),
        ),
        migrations.CreateModel(
            name="Teaching",
            fields=[],
            options={
                "proxy": True,
                "indexes": [],
                "constraints": [],
            },
            bases=("content.contentitem",),
        ),
        migrations.CreateModel(
            name="Writing",
            fields=[],
            options={
                "proxy": True,
                "indexes": [],
                "constraints": [],
            },
            bases=("content.contentitem",),
        ),
        migrations.CreateModel(
            name="VideoAttachment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("object_id", models.PositiveIntegerField()),
                (
                    "label",
                    models.CharField(
                        blank=True, help_text='e.g. "Video 1"', max_length=40
                    ),
                ),
                ("order", models.PositiveIntegerField(default=0)),
                ("is_primary", models.BooleanField(default=False)),
                (
                    "content_type",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="contenttypes.contenttype",
                    ),
                ),
                (
                    "video",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="attachments",
                        to="content.video",
                    ),
                ),
            ],
            options={
                "ordering": ["order"],
            },
        ),
        migrations.AddIndex(
            model_name="contentitem",
            index=models.Index(
                fields=["kind", "status", "-published_at"],
                name="content_con_kind_22a815_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="contentitem",
            index=models.Index(
                fields=["status", "needs_review"], name="content_con_status_56fc4a_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="videoattachment",
            index=models.Index(
                fields=["content_type", "object_id"],
                name="content_vid_content_c67ace_idx",
            ),
        ),
        migrations.AddConstraint(
            model_name="videoattachment",
            constraint=models.UniqueConstraint(
                fields=("video", "content_type", "object_id"),
                name="uniq_video_attachment",
            ),
        ),
    ]
