# Generated by Django 5.2.11 on 2026-09-30 20:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contentitem',
            name='date_source',
            field=models.CharField(choices=[('title_parsed', 'Parsed from title'), ('video', "From the video's upload date"), ('manual', 'Entered by staff'), ('unknown', 'Undated')], default='unknown', max_length=16),
        ),
    ]
