# Generated by Django 5.2.11 on 2026-09-16 16:56

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="SalvationDecision",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "decision",
                    models.CharField(
                        choices=[
                            ("prayed", "I prayed"),
                            ("not_yet", "Not yet"),
                            ("has_questions", "I have questions"),
                            ("recommitment", "Recommitment"),
                        ],
                        db_index=True,
                        max_length=16,
                    ),
                ),
                ("name", models.CharField(blank=True, max_length=200)),
                ("email", models.EmailField(blank=True, max_length=254)),
                ("phone", models.CharField(blank=True, max_length=40)),
                ("country", models.CharField(blank=True, max_length=80)),
                ("message", models.TextField(blank=True)),
                (
                    "reason",
                    models.CharField(
                        blank=True,
                        help_text="For 'not yet': what is holding them back.",
                        max_length=60,
                    ),
                ),
                ("language", models.CharField(default="en", max_length=8)),
                ("step_reached", models.PositiveSmallIntegerField(default=0)),
                ("referral_path", models.CharField(blank=True, max_length=300)),
                ("wants_follow_up", models.BooleanField(default=False)),
                ("consent_text_version", models.CharField(blank=True, max_length=20)),
                ("consented_at", models.DateTimeField(blank=True, null=True)),
                ("ip_hash", models.CharField(blank=True, max_length=64)),
                (
                    "follow_up_status",
                    models.CharField(
                        choices=[
                            ("new", "New"),
                            ("in_progress", "In progress"),
                            ("done", "Completed"),
                            ("no_contact", "No contact details"),
                        ],
                        db_index=True,
                        default="new",
                        max_length=16,
                    ),
                ),
                ("follow_up_notes", models.TextField(blank=True)),
                ("retention_expires_at", models.DateTimeField(db_index=True)),
                ("anonymised_at", models.DateTimeField(blank=True, null=True)),
                (
                    "assigned_to",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="salvation_followups",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "salvation decision",
                "ordering": ["-created_at"],
            },
        ),
    ]
