# Generated by Django 5.2.11 on 2026-09-30 20:39

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('media', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Gallery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(help_text='For staff; not shown on the site.', max_length=200)),
                ('eyebrow', models.CharField(default='Recognition', max_length=60)),
                ('heading', models.CharField(help_text='Wrap words in **double stars** to set them in yellow.', max_length=200)),
                ('place_name', models.CharField(blank=True, max_length=80)),
                ('place_detail', models.CharField(blank=True, max_length=80)),
                ('summary', models.TextField(blank=True, max_length=600)),
                ('is_featured', models.BooleanField(default=False, help_text='Shown on the home page. Only one gallery can be.')),
            ],
            options={
                'verbose_name_plural': 'galleries',
                'ordering': ['-is_featured', '-updated_at'],
                'constraints': [models.UniqueConstraint(condition=models.Q(('is_featured', True)), fields=('is_featured',), name='one_featured_gallery')],
            },
        ),
        migrations.CreateModel(
            name='GalleryPhoto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=120)),
                ('caption', models.CharField(blank=True, max_length=400)),
                ('alt_text', models.CharField(blank=True, help_text="Leave empty to use the photo's own description.", max_length=300)),
                ('order', models.PositiveIntegerField(default=0)),
                ('gallery', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='sitecontent.gallery')),
                ('image', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='gallery_photos', to='media.mediaasset')),
            ],
            options={
                'verbose_name': 'gallery photo',
                'ordering': ['order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='HeroSlide',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('alt_text', models.CharField(blank=True, help_text="Leave empty to use the photo's own description.", max_length=300)),
                ('place', models.CharField(help_text='Yellow block of the place tag.', max_length=60)),
                ('detail', models.CharField(blank=True, help_text='Navy block of the place tag, e.g. the country.', max_length=60)),
                ('event', models.CharField(max_length=80)),
                ('frame_x', models.FloatField(default=0.5, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(1.0)])),
                ('frame_y', models.FloatField(default=0.3, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(1.0)])),
                ('frame_lg_x', models.FloatField(default=0.5, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(1.0)])),
                ('frame_lg_y', models.FloatField(default=0.25, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(1.0)])),
                ('order', models.PositiveIntegerField(db_index=True, default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('image', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='hero_slides', to='media.mediaasset')),
            ],
            options={
                'verbose_name': 'hero slide',
                'ordering': ['order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='SiteSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=64, unique=True)),
                ('data', models.JSONField(default=dict)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'site text',
                'verbose_name_plural': 'site text',
                'ordering': ['key'],
            },
        ),
    ]
