# Generated by Django 5.2.11 on 2026-09-30 20:39

import apps.media.models
import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MediaAsset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('file', models.ImageField(height_field='height', max_length=255, upload_to=apps.media.models.asset_path, width_field='width')),
                ('title', models.CharField(max_length=200)),
                ('alt_text', models.CharField(blank=True, help_text='What the photo shows, for someone who cannot see it.', max_length=300)),
                ('caption', models.TextField(blank=True, max_length=1000)),
                ('credit', models.CharField(blank=True, max_length=200)),
                ('collection', models.CharField(blank=True, db_index=True, help_text='A folder to find it by, e.g. "Hero" or "Bogotá 2026".', max_length=80)),
                ('focal_x', models.FloatField(default=0.5, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(1.0)])),
                ('focal_y', models.FloatField(default=0.5, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(1.0)])),
                ('width', models.PositiveIntegerField(default=0)),
                ('height', models.PositiveIntegerField(default=0)),
                ('file_size', models.PositiveIntegerField(default=0)),
                ('original_filename', models.CharField(blank=True, max_length=255)),
                ('checksum', models.CharField(blank=True, db_index=True, max_length=64)),
                ('uploaded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'photo',
                'ordering': ['-created_at'],
            },
        ),
    ]
